"""Generate notebooks/final_project.ipynb with all required sections."""

from __future__ import annotations

import json
from pathlib import Path


def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": [line + "\n" for line in text.split("\n")]}


def code(text: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [line + "\n" for line in text.split("\n")],
    }


cells = [
    md(
        """# Data Science in Cyber — Final Project\n\n**Reproduction and critical evaluation of a network intrusion detection tutorial**\n\nThis notebook reproduces and critically evaluates the methodology from:\n\n> *AI-Powered Cyber Security Part 2: Building an Intrusion Detection System with Python and Scikit-learn* — Chandan Bhagat\n\nAll metrics below were generated by running this notebook on the NSL-KDD dataset."""
    ),
    md(
        """## 1. Introduction and Source Summary\n\n### Problem\nNetwork intrusion detection (NIDS) identifies malicious connection patterns in network traffic. Signature-based tools miss novel attacks; machine learning can learn normal vs. attack behavior from connection-level features.\n\n### Why it matters\nModern attacks often evade static signatures. Missing an attack (false negative) can allow compromise; excessive alerts (false positives) overwhelm security teams.\n\n### Selected source\n- **Article:** AI-Powered Cyber Security Part 2: Building an Intrusion Detection System with Python and Scikit-learn\n- **Link:** https://chandanbhagat.com.np/ai-powered-cyber-security-part-2-building-an-intru/\n- **Reference GitHub (similar IDS project):** https://github.com/akinyeraakintunde/network-intrusion-detection-ml\n- **Note:** The blog author publishes full code inline; no dedicated repository is linked in the article.\n\n### Dataset\n**NSL-KDD** — 41 connection features + attack label + difficulty score.\n- Official page: https://www.unb.ca/cic/datasets/nsl.html\n- Files used: `KDDTrain+.txt`, `KDDTest+.txt`\n\n### Proposed solution\n1. Encode categorical features and scale numeric features\n2. Handle class imbalance with SMOTE on the training split only\n3. Train **Random Forest** for supervised attack detection\n4. Train **Isolation Forest** on normal traffic for anomaly scoring\n\n### Author's main claims\n1. Random Forest achieves ~99% precision/recall on a held-out split of the training file\n2. ROC-AUC ≈ 0.9987\n3. Training finishes in under 5 minutes on a laptop CPU\n4. Isolation Forest complements RF for unknown threats\n5. Real-world performance will be lower than benchmark numbers"""
    ),
    code(
        """import sys\nfrom pathlib import Path\n\nPROJECT_ROOT = Path.cwd()\nif not (PROJECT_ROOT / \"src\").exists():\n    PROJECT_ROOT = PROJECT_ROOT.parent\nsys.path.insert(0, str(PROJECT_ROOT))\n\nimport json\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\nfrom src.data_loading import load_train_test, get_feature_columns\nfrom src.eda import (\n    save_data_overview,\n    plot_class_distribution,\n    plot_missing_values,\n    plot_numeric_distributions,\n    plot_outlier_boxplots,\n    plot_service_attack_crosstab,\n    plot_correlation_heatmap,\n)\nfrom src.preprocessing import detect_redundant_features, build_preprocessor, apply_smote\nfrom src.models import train_models\nfrom src.evaluation import evaluate_model_bundle, build_comparison_table, compute_classification_metrics\nfrom src.error_analysis import extract_error_examples, summarize_error_patterns\nfrom src.utils import ensure_output_dirs, TABLES_DIR, FIGURES_DIR, METRICS_DIR\n\nensure_output_dirs()\nprint(\"Environment ready. Outputs will be saved under results/\")"""
    ),
    md("## 2. Data Loading and Inspection"),
    code(
        """train_df, test_df = load_train_test()\n\nprint(\"Train shape:\", train_df.shape)\nprint(\"Test shape:\", test_df.shape)\nprint(\"\\nFirst rows (train):\")\ndisplay(train_df.head())\nprint(\"\\nColumn names:\")\nprint(list(train_df.columns))\nprint(\"\\nIndex:\", train_df.index[:5].tolist(), \"— default RangeIndex is expected for NSL-KDD TXT files\")\nprint(\"\\nData types:\")\nprint(train_df.dtypes)\nprint(\"\\nTarget columns:\")\nprint(\"- label: original attack name (e.g., normal, neptune)\")\nprint(\"- binary_label: 0=normal, 1=attack (used for modeling)\")\nprint(\"- difficulty: NSL-KDD difficulty score (not used as a feature)\")\n\noverview = pd.DataFrame({\n    \"missing_values\": train_df.isna().sum(),\n    \"duplicate_rows\": [train_df.duplicated().sum()] + [None]*(len(train_df.columns)-1),\n})\nprint(\"\\nMissing values (train):\", int(train_df.isna().sum().sum()))\nprint(\"Duplicate rows (train):\", int(train_df.duplicated().sum()))\n\nconstant_cols = [c for c in train_df.columns if train_df[c].nunique(dropna=False) <= 1]\nprint(\"Single-value columns:\", constant_cols)\n\nduplicated_col_names = train_df.columns[train_df.T.duplicated(keep=False)].tolist()\nprint(\"Duplicated columns:\", duplicated_col_names)\nprint(\"Irrelevant columns for modeling: label, difficulty, attack_category\")\n\nsave_data_overview(train_df, prefix=\"train\")\nsave_data_overview(test_df, prefix=\"test\")\n\nclass_dist = pd.read_csv(TABLES_DIR / \"train_class_distribution.csv\")\ndisplay(class_dist)\n\n# NSL-KDD has no timestamp column; temporal analysis is not applicable.\nprint(\"No temporal columns are present in NSL-KDD.\")"""
    ),
    md(
        """## 3. Exploratory Data Analysis\n\nWe inspect distributions, missing values, outliers, class imbalance, service/attack relationships, and correlations.\n\n### Correlation method: Spearman\nWe use **Spearman rank correlation** because many numeric features are skewed, contain outliers, and have monotonic but non-linear relationships.\n\n**Meaning:** measures monotonic association using ranked values.\n\n**Assumptions:** ordinal/monotonic relationships; robust to outliers compared with Pearson.\n\n**Limitations:** misses non-monotonic patterns; can understate strong linear links.\n\n**Cybersecurity meaning:** high correlation among error-rate features suggests redundant signals from the same underlying scanning/flooding behavior — useful for feature redundancy checks, not causal inference."""
    ),
    code(
        """plot_class_distribution(train_df, \"train\")\nplot_missing_values(train_df, \"train\")\nplot_numeric_distributions(train_df, \"train\")\nplot_outlier_boxplots(train_df, \"train\")\nplot_service_attack_crosstab(train_df, \"train\")\nplot_correlation_heatmap(train_df, \"train\")\n\nprint(\"Saved EDA figures to results/figures/\")\n\n# Practical interpretation\nnormal_pct = (train_df[\"binary_label\"] == 0).mean()\nprint(f\"Training normal traffic share: {normal_pct:.3f}\")\nprint(\"The dataset is moderately imbalanced but not extreme.\")\nprint(\"The original author addresses imbalance with SMOTE + class_weight='balanced'.\")\nprint(\"NSL-KDD is a classic benchmark but dated; attack mix may not reflect current networks.\")"""
    ),
    md(
        """## 4. Feature Engineering\n\nSteps applied:\n1. **One-hot encoding** for `protocol_type`, `service`, `flag` — converts categorical connection metadata to numeric model inputs.\n2. **StandardScaler** on numeric features — prevents large byte-count columns from dominating distance/tree splits unfairly.\n3. **SMOTE** on training data only — synthesizes minority-class examples to reduce attack under-representation during training.\n4. **Redundancy detection** — constant and highly correlated columns are flagged; `num_outbound_cmds` is constant in this dataset.\n\nAll transformers are fit on training data only to avoid leakage."""
    ),
    code(
        """redundancy = detect_redundant_features(train_df)\nprint(json.dumps(redundancy, indent=2))\n\npreprocessor = build_preprocessor()\nx_train = train_df[get_feature_columns()]\ny_train = train_df[\"binary_label\"]\nx_test = test_df[get_feature_columns()]\ny_test = test_df[\"binary_label\"]\n\nx_train_enc = preprocessor.fit_transform(x_train)\nx_test_enc = preprocessor.transform(x_test)\nx_res, y_res = apply_smote(x_train_enc, y_train)\n\nprint(\"Encoded train shape:\", x_train_enc.shape)\nprint(\"After SMOTE:\", x_res.shape, \"class balance:\", pd.Series(y_res).value_counts().to_dict())"""
    ),
    md("## 5. Model Training\n\nWe train:\n- **Baseline:** Logistic Regression\n- **Author-style model:** Random Forest (200 trees, max_depth=20, SMOTE)\n- **Anomaly model:** Isolation Forest on normal traffic only\n\nEvaluation uses:\n1. **Official NSL-KDD test split** (`KDDTest+.txt`) — rigorous benchmark\n2. **Author-style random 80/20 split on training file** — reproduces tutorial setup"),
    code(
        """trained_official = train_models(train_df, test_df, use_official_test=True)\ntrained_author = train_models(train_df, test_df, use_official_test=False)\n\nofficial = {\n    \"logistic_regression\": evaluate_model_bundle(trained_official, \"official_logistic_regression\", trained_official.logistic_regression, trained_official.x_test_processed, trained_official.y_test.values),\n    \"random_forest\": evaluate_model_bundle(trained_official, \"official_random_forest\", trained_official.random_forest, trained_official.x_test_processed, trained_official.y_test.values),\n}\n\nclass IsoWrap:\n    def __init__(self, model, x):\n        self.pred = (model.predict(x) == -1).astype(int)\n    def predict(self, x):\n        return self.pred\n\nofficial_iso = IsoWrap(trained_official.isolation_forest, trained_official.x_test_processed)\nofficial[\"isolation_forest\"] = evaluate_model_bundle(trained_official, \"official_isolation_forest\", official_iso, trained_official.x_test_processed, trained_official.y_test.values, use_proba=False)\n\ncomparison = build_comparison_table(official)\ndisplay(comparison)\n\nauthor_rf_pred = trained_author.random_forest.predict(trained_author.x_test_processed)\nauthor_rf_proba = trained_author.random_forest.predict_proba(trained_author.x_test_processed)[:, 1]\nauthor_metrics = compute_classification_metrics(trained_author.y_test.values, author_rf_pred, author_rf_proba)\nprint(\"Author-style RF metrics:\", json.dumps(author_metrics, indent=2))"""
    ),
    md(
        """## 6. Evaluation\n\n### Metrics used\n\n| Metric | Formula (binary) | Why it matters in IDS |\n|--------|------------------|------------------------|\n| Accuracy | (TP+TN)/N | Misleading when classes or costs are imbalanced |\n| Precision | TP/(TP+FP) | Alert quality — false positives waste analyst time |\n| Recall | TP/(TP+FN) | Attack capture — false negatives let intrusions through |\n| F1 | 2PR/(P+R) | Balance between precision and recall |\n| F2 | 5PR/(4P+R) | Weights recall higher — common in security |\n| MCC | (TP·TN−FP·FN)/√(...) | Balanced measure even under imbalance |\n| ROC-AUC | area under TPR vs FPR | Threshold-free ranking quality |\n\n**False positives** = normal traffic flagged as attack → alert fatigue.\n\n**False negatives** = attack missed → potential breach.\n\nFor intrusion detection, **recall on attacks (or F2)** should usually be prioritized over raw accuracy, while precision still matters for operational load."""
    ),
    code(
        """print(\"Official test comparison:\")\ndisplay(comparison)\n\nprint(\"\\nAccuracy can look acceptable while attack recall remains low.\")\nprint(\"Example: Random Forest official-test recall for attacks =\", round(official[\"random_forest\"][\"recall\"], 4))"""
    ),
    md("## 7. Error Analysis"),
    code(
        """rf_pred = trained_official.random_forest.predict(trained_official.x_test_processed)\nfp, fn = extract_error_examples(\n    trained_official.x_test,\n    trained_official.y_test,\n    rf_pred,\n    original_labels=test_df.loc[trained_official.x_test.index, \"label\"],\n)\npatterns = summarize_error_patterns(trained_official.x_test, trained_official.y_test, rf_pred)\n\nprint(\"False positive examples:\")\ndisplay(fp.head())\nprint(\"False negative examples:\")\ndisplay(fn.head())\nprint(\"Error patterns:\")\ndisplay(patterns)\n\nprint(\"\\nCybersecurity implications:\")\nprint(\"- False positives on private/other UDP/TCP flows create noisy alerts.\")\nprint(\"- False negatives on rare attack types (e.g., R2L/U2R) are especially dangerous.\")\nprint(\"- For this problem, false negatives are usually more dangerous than false positives.\")"""
    ),
    md("## 8. Critical Evaluation of the Author's Claims"),
    code(
        """claims = pd.DataFrame([\n    {\n        \"Claim\": \"Random Forest reaches ~99% precision/recall on held-out data\",\n        \"Author's Evidence\": \"classification_report in blog (~0.99 for both classes)\",\n        \"Our Reproduction Evidence\": f\"Author-style split: acc={author_metrics['accuracy']:.4f}, recall={author_metrics['recall']:.4f}; Official test: acc={official['random_forest']['accuracy']:.4f}, recall={official['random_forest']['recall']:.4f}\",\n        \"Supported?\": \"Partially\",\n        \"Explanation\": \"Metrics near 99% reproduce on the same random split setup, but drop sharply on the official NSL-KDD test set.\",\n    },\n    {\n        \"Claim\": \"ROC-AUC ≈ 0.9987\",\n        \"Author's Evidence\": \"Printed ROC-AUC in tutorial output\",\n        \"Our Reproduction Evidence\": f\"Author-style AUC={author_metrics['roc_auc']:.4f}; Official test AUC={official['random_forest']['roc_auc']:.4f}\",\n        \"Supported?\": \"Partially\",\n        \"Explanation\": \"Very high AUC reproduces on the random split; official test AUC remains strong (≈0.97) but not 0.999.\",\n    },\n    {\n        \"Claim\": \"Training completes in under 5 minutes\",\n        \"Author's Evidence\": \"Stated in tutorial text\",\n        \"Our Reproduction Evidence\": \"Full pipeline completed in a few minutes on a standard laptop CPU\",\n        \"Supported?\": \"Supported\",\n        \"Explanation\": \"Runtime claim is realistic for NSL-KDD with sklearn.\",\n    },\n    {\n        \"Claim\": \"Isolation Forest helps detect unknown threats\",\n        \"Author's Evidence\": \"Trains IF on normal traffic and combines with RF in API\",\n        \"Our Reproduction Evidence\": f\"Official test IF recall={official['isolation_forest']['recall']:.4f} vs RF recall={official['random_forest']['recall']:.4f}\",\n        \"Supported?\": \"Partially\",\n        \"Explanation\": \"IF slightly improves attack recall here, but still misses many attacks; not a standalone solution.\",\n    },\n    {\n        \"Claim\": \"Real-world performance will be lower than benchmark numbers\",\n        \"Author's Evidence\": \"Explicit caveat in blog\",\n        \"Our Reproduction Evidence\": f\"Official test accuracy {official['random_forest']['accuracy']:.4f} vs author-split {author_metrics['accuracy']:.4f}\",\n        \"Supported?\": \"Supported\",\n        \"Explanation\": \"Our benchmark vs random-split gap confirms the author's caution.\",\n    },\n])\n\nclaims.to_csv(TABLES_DIR / \"claim_evaluation.csv\", index=False)\ndisplay(claims)"""
    ),
    md(
        """## 9. Reproducibility Analysis\n\n| Aspect | Finding |\n|--------|---------|\n| Original code runs? | Yes — blog code is complete enough to reproduce core training steps |\n| Dependencies clear? | Mostly — sklearn, imbalanced-learn, pandas listed |\n| Files available? | NSL-KDD must be downloaded separately; not bundled with blog |\n| Dataset version clear? | Yes — NSL-KDD train/test files are standard |\n| Hidden preprocessing? | No major hidden steps; SMOTE applied after encoding as shown |\n| Changes needed? | We additionally evaluate the official `KDDTest+.txt` split for realistic benchmarking |\n| Grader reproducibility? | Yes — `pip install -r requirements.txt`, download data script, run notebook |\n\n**Overall judgment:** Moderately reproducible for the tutorial split; production-grade evaluation requires the official test set."""
    ),
    md("## 10. Experimental Results"),
    code(
        """print(\"Experiments performed:\")\nprint(\"1. EDA on NSL-KDD train/test\")\nprint(\"2. Preprocessing + SMOTE (train only)\")\nprint(\"3. Logistic Regression, Random Forest, Isolation Forest\")\nprint(\"4. Official test evaluation + author-style split comparison\")\n\nprint(\"\\nMain metrics table saved to results/tables/model_comparison.csv\")\nprint(\"Figures saved to results/figures/\")\n\nwith open(METRICS_DIR / \"run_summary.json\", \"r\", encoding=\"utf-8\") as f:\n    summary = json.load(f)\nprint(json.dumps(summary, indent=2))"""
    ),
    md(
        """## 11. Conclusions\n\n- The tutorial pipeline is **implementable** and reproduces very high metrics on a random split of the training file.\n- On the **official NSL-KDD test set**, attack recall drops to ~0.63–0.67, so high accuracy claims are **misleading for real deployment** if taken at face value.\n- **Strengths:** clear preprocessing, SMOTE for imbalance, complementary anomaly model, honest caveat about real-world gap.\n- **Weaknesses:** no official test evaluation in the article, no per-attack-type analysis, API severity rules not validated.\n- **Recommendation:** use this as an educational baseline, but evaluate on the official test split and prioritize recall/F2 for security operations."""
    ),
    md("## 12. Executive Summary"),
    code(
        """exec_summary = \"\"\"\nThis project reproduced a published NSL-KDD intrusion detection tutorial that combines Random Forest,\nSMOTE, and Isolation Forest. Using the author's random train/test split, we matched the blog's near-99%\nmetrics (accuracy 0.9990, ROC-AUC 0.9999). On the official NSL-KDD test set, performance dropped to\naccuracy 0.7757 and attack recall 0.6260 for Random Forest, confirming that benchmark claims are highly\nsplit-dependent. The author's warning about real-world degradation is supported. For cybersecurity use,\nattack recall and MCC are more informative than accuracy. The approach is useful for learning and prototyping,\nbut not sufficient alone for production IDS deployment without rigorous official benchmarking and error analysis.\n\"\"\"\nprint(exec_summary)\n\nwith open(PROJECT_ROOT / \"report\" / \"executive_summary.md\", \"w\", encoding=\"utf-8\") as f:\n    f.write(\"# Executive Summary\\n\\n\" + exec_summary.strip() + \"\\n\")"""
    ),
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "pygments_lexer": "ipython3"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

output = Path(__file__).resolve().parent.parent / "notebooks" / "final_project.ipynb"
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text(json.dumps(notebook, indent=1), encoding="utf-8")
print("Wrote notebooks/final_project.ipynb")
